feat: add bookings and comments
mikhaeltatischev/java-shareit pull request #2
Opened 2023-06-28 10:29 UTC by mikhaeltatischev

2023-06-29 09:39 UTC, sergeymamonov requested changes
Исключение UserAlreadyExistsException где-то используется?

2023-06-29 09:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/exception/BookingAlreadyApprovedException.java
> +    private static String getMessage(Long id) {
Можно сделать без статического метода. Можно сделать константу в классе  с текстом "Booking with id: %d already approved".

И потом сделать log.info(String.format(MESSAGE, id));

Для информации, в логгере можно делать так log.info("Booking with id: {} already approved", id);

Лучше во всех классах ошибки уйти от статического метода.

2023-06-29 09:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Проверьте во всем коде, как вызывается метод equals.

2023-06-29 09:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/handler/GlobalExceptionHandler.java
> +    public AppError handleBookingTimeException(final NotValidStateException e) {
Невалидные данные это скорее HttpStatus.BAD_REQUEST, что внутренняя ошибка приложения.

2023-06-29 09:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .filter((booking) -> booking.getStartTime().isBefore(LocalDateTime.now()) && !booking.getStatus().equals(Status.REJECTED))
Лишние скобки вокруг booking

2023-06-29 09:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/exception/ItemRequestAlreadyExistsException.java
> +    public ItemRequestAlreadyExistsException(Long id) {
Эта ошибка где-то используется?

2023-06-29 09:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        return toDto(itemRequestRepository.findById(id).get());
Здесь и в строке 70 вызов метода get() без проверки может привести к NPE. Поэтому необходимо добавить проверку, посмотрите методы, которые есть в Optional для такой проверки.

2023-06-29 19:59 UTC, mikhaeltatischev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
Привет, честно не очень понял вашего совета(
У класса Booking поле status не может быть null, я его при создании объекта выставляю WAITING, в других ситуациях я посмотрел, там тоже не может прийти null, так как валидация не позволит. Это я про такое (рис.1), тут booking не может существовать без item, а item не может без user
![image](https://github.com/mikhaeltatischev/java-shareit/assets/117846573/9daaa167-5e2b-4f23-81d8-7e1e15242be9)

2023-06-30 20:00 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
Это практика вызова метода equals. Если один из сравниваемых элементов константа, то вызывают equals у константы. То есть если можно себе обезопасить, то лучше обезопасить.

2023-06-30 20:02 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
Про создание методов: если можно дать какое-то осмысленное емкое название методу с такой проверкой, то можно вынести. Код станет более читаемее. Если название методу с проверкой придумать не получается, то и смысла выделять не вижу, лучше оставить так и не городить метод с вымученным названием.

2023-06-30 20:08 UTC, sergeymamonov approved these changes

2023-06-30 20:08 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/handler/GlobalExceptionHandler.java
>  }
Но теперь нет проверки для ошибки во время выполнения (500 ошибка). Лучше добавить.

2023-07-02 18:51 UTC, merged